#execution_env=local
execution_env=remote

appURL =https://www.saucedemo.com/
username = standard_user
password = secret_sauce
ProductName = Sauce Labs Backpack
firstName=Rani
lastName=Patel
postalCode=396001